services: 
  hof_frontend:
    image: ezekiel0108/hof-branchina-frontend
    container_name: hof_frontend
    restart: unless-stopped
    networks:
      - front-back
  hof_backend:
    image: gkracket207/hof-branchina-backend
    container_name: hof_backend
    restart: unless-stopped
    networks:
      - front-back
      - back-db
    environment:
      - DB_HOST=hof_db
      - DB_DATABASE=hof_db
      - DB_USER=usr
      - DB_PASSWORD=${MARIADB_PW}
    depends_on:
      hof_db:
        condition: service_healthy
  hof_db:
    image: mariadb:latest
    container_name: hof_db
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PW_ROOT}
      - MARIADB_DATABASE=hof_db
      - MARIADB_USER=usr
      - MARIADB_PASSWORD=${MARIADB_PW}
    ports: 
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - back-db
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
  hof_caddy:
    image: caddy:latest
    container_name: hof_caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - logs:/var/log/caddy
    networks:
      - front-back
      - General_Purpose_Services_proxy

networks:
  front-back:
    external: false
  back-db:
    external: false
  General_Purpose_services_proxy:
    external: true

volumes:
  mariadb_data:
  caddy_data:
  caddy_config:
  logs:

